# Generated by Django 3.1 on 2020-09-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingroom',
            name='room_number',
            field=models.TextField(default='', max_length=32),
        ),
    ]
