# Generated by Django 3.1 on 2020-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='visit_count',
            new_name='visit',
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
