# Generated by Django 3.1 on 2020-09-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0002_auto_20200906_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeartBeat',
            new_name='Visit',
        ),
    ]
